### ISSUE TITLE
Feature. Add jsx/jsxs exports for babel automatic runtime

### ISSUE THREAD

**Issue by iamandrewluca** [vadimdemedes/dom-chef#64] opened 2020-07-21 19:23 UTC
> Automatic runtime is a feature available in v7.9.0. With this runtime enabled, the functions that JSX compiles to will be imported automatically.

When enabling automatic runtime for `@babel/plugin-transform-react-jsx`, you can change from what source to use jsx/jsxs functions that transform jsx

```json5
{
  "plugins": [
    [
      "@babel/plugin-transform-react-jsx",
      {
        "runtime": "automatic", // defaults to classic
        "importSource": "dom-chef" // defaults to react
      }
    ]
  ]
}
```

This will try to automatically use

```js
import { jsx, jsxs } from 'dom-chef'
```

**Related links:**

https://babeljs.io/docs/en/babel-plugin-transform-react-jsx
https://github.com/babel/babel/pull/11154
https://github.com/facebook/react/blob/master/packages/react/jsx-runtime.js
https://unpkg.io/browse/react@0.0.0-experimental-aae83a4b9/

**Comment by fregante** [comment] 2020-07-21 19:28
Duplicate of https://github.com/vadimdemedes/dom-chef/issues/57

**Closed by fregante** 2020-07-21 19:28 UTC

**Comment by iamandrewluca** [comment] 2020-07-21 19:30
I want to slap myself ) Why I didn't look at opened issues )
Thanks!
